# Site settings
title: Allen's Blog
header-img: img/home-bg.jpg
email: phpip.simon@gmail.com
copyright_name: fyee
description: "一个技术宅的技术记录"
keywords: "php js linux docker"
baseurl: ""
url: "https://fyee.github.io"
twitter_username: Allen_Allen_Lau
github_username:  fyee
facebook_username:
email_username:  phpip.simon@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

kramdown:
  input: GFM